export const BIBLE_BOOKS = [
  // Old Testament
  { id: 1, name: "Genesis", tamilName: "ஆதியாகமம்", chapters: 50, testament: "Old" },
  { id: 2, name: "Exodus", tamilName: "யாத்திராகமம்", chapters: 40, testament: "Old" },
  { id: 3, name: "Leviticus", tamilName: "லேவியராகமம்", chapters: 27, testament: "Old" },
  { id: 4, name: "Numbers", tamilName: "எண்ணாகமம்", chapters: 36, testament: "Old" },
  { id: 5, name: "Deuteronomy", tamilName: "உபாகமம்", chapters: 34, testament: "Old" },
  { id: 6, name: "Joshua", tamilName: "யோசுவா", chapters: 24, testament: "Old" },
  { id: 7, name: "Judges", tamilName: "நியாயாதிபதிகள்", chapters: 21, testament: "Old" },
  { id: 8, name: "Ruth", tamilName: "ரூத்", chapters: 4, testament: "Old" },
  { id: 9, name: "1 Samuel", tamilName: "1 சாமுவேல்", chapters: 31, testament: "Old" },
  { id: 10, name: "2 Samuel", tamilName: "2 சாமுவேல்", chapters: 24, testament: "Old" },
  { id: 11, name: "1 Kings", tamilName: "1 இராஜாக்கள்", chapters: 22, testament: "Old" },
  { id: 12, name: "2 Kings", tamilName: "2 இராஜாக்கள்", chapters: 25, testament: "Old" },
  { id: 13, name: "1 Chronicles", tamilName: "1 நாளாகமம்", chapters: 29, testament: "Old" },
  { id: 14, name: "2 Chronicles", tamilName: "2 நாளாகமம்", chapters: 36, testament: "Old" },
  { id: 15, name: "Ezra", tamilName: "எஸ்றா", chapters: 10, testament: "Old" },
  { id: 16, name: "Nehemiah", tamilName: "நெகேமியா", chapters: 13, testament: "Old" },
  { id: 17, name: "Esther", tamilName: "எஸ்தர்", chapters: 10, testament: "Old" },
  { id: 18, name: "Job", tamilName: "யோபு", chapters: 42, testament: "Old" },
  { id: 19, name: "Psalms", tamilName: "சங்கீதம்", chapters: 150, testament: "Old" },
  { id: 20, name: "Proverbs", tamilName: "நீதிமொழிகள்", chapters: 31, testament: "Old" },
  { id: 21, name: "Ecclesiastes", tamilName: "பிரசங்கி", chapters: 12, testament: "Old" },
  { id: 22, name: "Song of Solomon", tamilName: "உன்னதப்பாட்டு", chapters: 8, testament: "Old" },
  { id: 23, name: "Isaiah", tamilName: "ஏசாயா", chapters: 66, testament: "Old" },
  { id: 24, name: "Jeremiah", tamilName: "எரேமியா", chapters: 52, testament: "Old" },
  { id: 25, name: "Lamentations", tamilName: "புலம்பல்", chapters: 5, testament: "Old" },
  { id: 26, name: "Ezekiel", tamilName: "எசேக்கியேல்", chapters: 48, testament: "Old" },
  { id: 27, name: "Daniel", tamilName: "தானியேல்", chapters: 12, testament: "Old" },
  { id: 28, name: "Hosea", tamilName: "ஓசியா", chapters: 14, testament: "Old" },
  { id: 29, name: "Joel", tamilName: "யோவேல்", chapters: 3, testament: "Old" },
  { id: 30, name: "Amos", tamilName: "ஆமோஸ்", chapters: 9, testament: "Old" },
  { id: 31, name: "Obadiah", tamilName: "ஒபதியா", chapters: 1, testament: "Old" },
  { id: 32, name: "Jonah", tamilName: "யோனா", chapters: 4, testament: "Old" },
  { id: 33, name: "Micah", tamilName: "மீகா", chapters: 7, testament: "Old" },
  { id: 34, name: "Nahum", tamilName: "நாகூம்", chapters: 3, testament: "Old" },
  { id: 35, name: "Habakkuk", tamilName: "ஆபகூக்", chapters: 3, testament: "Old" },
  { id: 36, name: "Zephaniah", tamilName: "செப்பனியா", chapters: 3, testament: "Old" },
  { id: 37, name: "Haggai", tamilName: "ஆகாய்", chapters: 2, testament: "Old" },
  { id: 38, name: "Zechariah", tamilName: "சகரியா", chapters: 14, testament: "Old" },
  { id: 39, name: "Malachi", tamilName: "மல்கியா", chapters: 4, testament: "Old" },
  // New Testament
  { id: 40, name: "Matthew", tamilName: "மத்தேயு", chapters: 28, testament: "New" },
  { id: 41, name: "Mark", tamilName: "மாற்கு", chapters: 16, testament: "New" },
  { id: 42, name: "Luke", tamilName: "லூக்கா", chapters: 24, testament: "New" },
  { id: 43, name: "John", tamilName: "யோவான்", chapters: 21, testament: "New" },
  { id: 44, name: "Acts", tamilName: "அப்போஸ்தலர்", chapters: 28, testament: "New" },
  { id: 45, name: "Romans", tamilName: "ரோமர்", chapters: 16, testament: "New" },
  { id: 46, name: "1 Corinthians", tamilName: "1 கொரிந்தியர்", chapters: 16, testament: "New" },
  { id: 47, name: "2 Corinthians", tamilName: "2 கொரிந்தியர்", chapters: 13, testament: "New" },
  { id: 48, name: "Galatians", tamilName: "கலாத்தியர்", chapters: 6, testament: "New" },
  { id: 49, name: "Ephesians", tamilName: "எபேசியர்", chapters: 6, testament: "New" },
  { id: 50, name: "Philippians", tamilName: "பிலிப்பியர்", chapters: 4, testament: "New" },
  { id: 51, name: "Colossians", tamilName: "கொலோசெயர்", chapters: 4, testament: "New" },
  { id: 52, name: "1 Thessalonians", tamilName: "1 தெசலோனிக்கேயர்", chapters: 5, testament: "New" },
  { id: 53, name: "2 Thessalonians", tamilName: "2 தெசலோனிக்கேயர்", chapters: 3, testament: "New" },
  { id: 54, name: "1 Timothy", tamilName: "1 தீமோத்தேயு", chapters: 6, testament: "New" },
  { id: 55, name: "2 Timothy", tamilName: "2 தீமோத்தேயு", chapters: 4, testament: "New" },
  { id: 56, name: "Titus", tamilName: "தீத்து", chapters: 3, testament: "New" },
  { id: 57, name: "Philemon", tamilName: "பிலேமோன்", chapters: 1, testament: "New" },
  { id: 58, name: "Hebrews", tamilName: "எபிரெயர்", chapters: 13, testament: "New" },
  { id: 59, name: "James", tamilName: "யாக்கோபு", chapters: 5, testament: "New" },
  { id: 60, name: "1 Peter", tamilName: "1 பேதுரு", chapters: 5, testament: "New" },
  { id: 61, name: "2 Peter", tamilName: "2 பேதுரு", chapters: 3, testament: "New" },
  { id: 62, name: "1 John", tamilName: "1 யோவான்", chapters: 5, testament: "New" },
  { id: 63, name: "2 John", tamilName: "2 யோவான்", chapters: 1, testament: "New" },
  { id: 64, name: "3 John", tamilName: "3 யோவான்", chapters: 1, testament: "New" },
  { id: 65, name: "Jude", tamilName: "யூதா", chapters: 1, testament: "New" },
  { id: 66, name: "Revelation", tamilName: "வெளிப்படுத்தின விசேஷம்", chapters: 22, testament: "New" },
];

export const TOTAL_CHAPTERS = 1189;
export const OT_CHAPTERS = 929;
export const NT_CHAPTERS = 260;
